// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB67vOvTWJ5WAqxBWd8zYcwOLHu_h58gaY',
    appId: '1:1092083745694:web:33d702419f59c367664c8f',
    messagingSenderId: '1092083745694',
    projectId: 'app-mov2-api-41b79',
    authDomain: 'app-mov2-api-41b79.firebaseapp.com',
    databaseURL: 'https://app-mov2-api-41b79-default-rtdb.firebaseio.com',
    storageBucket: 'app-mov2-api-41b79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1tekRY6mauNxu4PNZVQghxE08A6UL8is',
    appId: '1:1092083745694:android:d98537afcedea579664c8f',
    messagingSenderId: '1092083745694',
    projectId: 'app-mov2-api-41b79',
    databaseURL: 'https://app-mov2-api-41b79-default-rtdb.firebaseio.com',
    storageBucket: 'app-mov2-api-41b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV8QEgwcE4zbGi_uZyIaasDSOC4tMxxNU',
    appId: '1:1092083745694:ios:665dfabd6b9dd5ff664c8f',
    messagingSenderId: '1092083745694',
    projectId: 'app-mov2-api-41b79',
    databaseURL: 'https://app-mov2-api-41b79-default-rtdb.firebaseio.com',
    storageBucket: 'app-mov2-api-41b79.appspot.com',
    iosBundleId: 'com.example.prueba2PaolaTamayo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV8QEgwcE4zbGi_uZyIaasDSOC4tMxxNU',
    appId: '1:1092083745694:ios:665dfabd6b9dd5ff664c8f',
    messagingSenderId: '1092083745694',
    projectId: 'app-mov2-api-41b79',
    databaseURL: 'https://app-mov2-api-41b79-default-rtdb.firebaseio.com',
    storageBucket: 'app-mov2-api-41b79.appspot.com',
    iosBundleId: 'com.example.prueba2PaolaTamayo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB67vOvTWJ5WAqxBWd8zYcwOLHu_h58gaY',
    appId: '1:1092083745694:web:6f551a0decaa4653664c8f',
    messagingSenderId: '1092083745694',
    projectId: 'app-mov2-api-41b79',
    authDomain: 'app-mov2-api-41b79.firebaseapp.com',
    databaseURL: 'https://app-mov2-api-41b79-default-rtdb.firebaseio.com',
    storageBucket: 'app-mov2-api-41b79.appspot.com',
  );

}